modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/bubbleboots/issues"
license = "MIT License"

[[mods]]
modId = "bubble_boots"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "supplementaries:soap"
configBackground = "supplementaries:textures/blocks/soap_block.png"
authors = "DavigJ"
credits = "Thanks to the Supplementaries team, MehVahdJukaar for helping on code, and manuelaurreaf for the bubbles sound."
displayURL = ""
displayName = "Bubble Boots"
description = '''
    A Supplementaries add-on that has one bubbly new item.
    '''

[[dependencies.bubble_boots]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "blueprint"
mandatory = true
versionRange = "[7.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "moonlight"
mandatory = true
versionRange = "[1.20-2.9.16,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "supplementaries"
mandatory = true
versionRange = "[1.20-2.7.36,)"
ordering = "AFTER"
side = "BOTH"