modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/bubbleboots/issues"
license = "MIT License"

[[mixins]]
config = "bubble_boots.mixins.json"

[[mods]]
modId = "bubble_boots"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "supplementaries:soap"
configBackground = "supplementaries:textures/blocks/soap_block.png"
authors = "DavigJ"
credits = "Thanks to the Supplementaries team, MehVahdJukaar for helping on code, and manuelaurreaf for the bubbles sound."
displayURL = "https://modrinth.com/project/bubble_boots"
displayName = "Bubble Boots"
description = '''
    A Supplementaries add-on that has one bubbly new item.
    '''

[[dependencies.bubble_boots]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "moonlight"
type = "required"
versionRange = "[1.21-2.26.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bubble_boots]]
modId = "supplementaries"
type = "required"
versionRange = "[1.21-3.4.20,)"
ordering = "AFTER"
side = "BOTH"